countdown-time: 3
game-time: 200
warp-block-type-oni: DIAMOND_BLOCK
warp-block-type-spec: IRON_BLOCK
tp-location:
  oni:
    x: 75.0
    y: 4.0
    z: -60.0
  player:
    x: 75.0
    y: 4.0
    z: -60.0
money-amount: 20